export enum NotificationType {
	ERROR_ADMIN = 'ERROR_ADMIN',
	MB_REPORT = 'MB_REPORT',
	VEHICLE_EMPTY = 'VEHICLE_EMPTY',
	MAIL_SIGNUP_USER = 'MAIL_SIGNUP_USER',
	MAIL_CONFIRMATION_USER = 'MAIL_CONFIRMATION_USER',
	USER_VERIFIED = 'USER_VERIFIED',
	MB_TOPUP_RECEIPT = 'MB_TOPUP_RECEIPT',
	MB_RENT_RECEIPT = 'MB_RENT_RECEIPT',
	MB_VEHICLES_TO_SERVICE_ADMIN = 'MB_VEHICLES_TO_SERVICE_ADMIN',
	MB_RENT_NPS = 'MB_RENT_NPS'
}
